"""
Pi Manager - Cross-platform GUI for managing and launching Pi Coding Agent.
All agent capability comes from the official `pi` CLI; this app manages
providers/models/settings and launches full Pi sessions.
"""
from __future__ import annotations

# ── 以下分组是 core_* 子模块的**重新导出**。
# 它们在 core.py 内部一个都没被使用，纯转发，但**不能删**：
#   1. 下游按 `core.xxx` 调用；
#   2. 子模块对会被动 monkeypatch 的名字走 ``core.xxx`` 动态查找。
# ruff 的 F401 已通过 pyproject.toml 的 per-file-ignores 为本文件豁免。
from .core_http import (
    TRANSIENT_HTTP_MAX_ATTEMPTS,
    TRANSIENT_HTTP_STATUSES,
    _friendly_fetch_error,
    _ssl_context,
    is_transient_http_status,
    is_transient_upstream_error,
    normalize_openai_base_url,
    parse_retry_after_seconds,
    redact_endpoint_url,
    redact_secret_values,
    sleep_transient_retry,
    transient_retry_delay,
)
# 视觉识图管道已抽到 core_vision，此处重新导出以保持 core.xxx 调用兼容。
from .core_vision import (
    DEFAULT_VISION_PROMPT,
    ZHIPU_API_KEY_SECRET,
    ZHIPU_BASE_URL,
    ZHIPU_VISION_MODELS,
    build_vision_prompt,
    describe_image,
    ensure_zhipu_provider,
    install_vision_skill,
    load_image_for_describe,
    set_vision_model_choice,
    set_zhipu_api_key,
    test_vision,
    vision_model_choice,
    zhipu_api_key,
)
# 进程管理工具已抽到 core_process，此处重新导出以保持 core.xxx 调用兼容。
from .core_process import (
    _check_request_scheme,
    _is_private_host,
    _terminate_process_tree,
    escape_cmd_shim_args,
    find_pi_command,
    list_terminal_options,
    pi_base_cmd,
    proxy_reachable,
    redact_proxy_url,
    run_pi,
    sanitize_proxy_env,
    strip_pyinstaller_runtime_env,
    validate_launch_tokens,
    validate_proxy_url,
)
# 远程模型获取与 HTTP 连通性测试已抽到 core_remote，此处重新导出。
from .core_remote import (
    _extract_reply_preview,
    _http_json_request,
    _resolve_provider_runtime_key,
    fetch_remote_models,
    format_test_summary,
    test_model,
    test_model_http,
    test_model_via_pi,
)
# 会话管理已抽到 core_sessions，此处重新导出。
from .core_sessions import (
    _decode_session_folder_slug,
    _parse_session_meta,
    list_sessions,
    open_in_explorer,
    open_path,
    project_name_from_path,
)
# 凭据与 Provider 密钥已抽到 core_credentials，此处重新导出。
from .core_credentials import (
    ProviderKeyError,
    _is_provider_request_block_error,
    all_provider_runtime_env,
    classify_provider_key_failure,
    is_executable_config_value,
    is_provider_key_error,
    normalize_config_string,
    provider_key_failure_reason,
    provider_runtime_credential,
    provider_runtime_env,
    resolve_api_key_value,
)

from .core_paths import (
    auth_path,
    ensure_agent_dir,
    manager_config_path,
    models_path,
    pi_agent_dir,
    sessions_dir,
    settings_path,
    user_home,
)
from .core_store import (
    DEFAULT_OPENAI_COMPAT_USER_AGENT,
    _CONFIG_CACHE,
    _CONFIG_CACHE_LOCK,
    _CONFIG_CACHE_TTL,
    _MANAGER_UPGRADE_DEFAULTS,
    _MODELS_MIGRATED_SIGNATURE,
    _MODELS_MIGRATION_LOCK,
    _MODELS_MIGRATIONS,
    _OPENAI_COMPAT_APIS,
    _invalidate_config_cache,
    _load_config_with_recovery,
    _load_json_cached,
    _manager_config_defaults,
    _migrate_models_config,
    _migrate_models_defaults,
    _migrate_models_headers,
    _migrate_models_keys,
    _migrate_models_thinking,
    _models_file_signature,
    _normalize_manager_config,
    _openai_compat_headers,
    _repair_corrupt_config,
    _restore_latest_config_backup,
    _sanitize_models_config,
    _update_config,
    auth_summary,
    delete_provider_auth,
    load_auth,
    load_json,
    load_manager_config,
    load_models_config,
    load_settings,
    mask_secret,
    redact_sensitive_config,
    save_json,
    save_manager_config,
    save_models_config,
    save_settings,
    update_manager_config,
    update_models_config,
    update_settings,
)
from .core_catalog import (
    DEFAULT_THINKING_LEVEL,
    DEFAULT_THINKING_LEVEL_MAP,
    ModelInfo,
    add_model_to_provider,
    delete_custom_provider,
    ensure_thinking_level_map,
    fill_model_defaults,
    default_model_template,
    get_default_model,
    list_models,
    list_stale_enabled_models,
    normalize_model_pair,
    parse_favorite_key,
    purge_enabled_models,
    purge_favorites,
    remove_model_from_provider,
    set_default_model,
    set_enabled_models,
    upsert_custom_provider,
)
from .core_launch import build_pi_launch_args, launch_pi_interactive, run_pi_print
from .core_prefs import (
    LANG_EN_PROMPT,
    LANG_PROMPTS,
    LANG_ZH_PROMPT,
    _LANG_BLOCK_RE,
    _UI_ACCENTS,
    _helper_command_text,
    _normalize_ui_accent,
    _vision_rule_prompt,
    agents_md_path,
    append_language_args,
    append_vision_args,
    apply_language_preference,
    apply_theme,
    cli_theme_for_ui_mode,
    get_language,
    get_theme,
    get_ui_theme,
    is_setup_done,
    language_prompt_text,
    list_themes,
    mark_setup_done,
    normalize_ui_mode,
    run_first_time_bootstrap,
    set_language,
    set_ui_theme,
    sync_cli_theme_with_ui,
)
from .core_pi_runtime import (
    PI_LATEST_MIN_NODE,
    PI_LATEST_TAG,
    PI_LEGACY_MIN_NODE,
    PI_LEGACY_NODE20_TAG,
    PI_NPM_PACKAGE,
    _node_command,
    _npm_command,
    _run_version_command,
    check_pi_status,
    dismiss_update,
    get_installed_pi_version,
    get_latest_pi_version,
    get_node_version,
    get_npm_version,
    get_pi_runtime_status,
    get_pi_version,
    install_or_update_pi,
    is_update_dismissed,
    load_pi_update_status,
    needs_pi_install_or_update,
    parse_semver,
    pi_package_spec,
    pi_update_state,
    select_pi_install_channel,
)
from .core_admin import (
    _BACKUP_TARGETS,
    _effective_proxy_url,
    add_provider_api_key,
    delete_orphaned_provider_keys,
    get_provider_config,
    list_config_backups,
    list_orphaned_provider_keys,
    list_provider_api_keys,
    remove_provider_api_key,
    restore_all_provider_api_keys,
    restore_config_backup,
    restore_provider_api_key,
)
