# -*- coding: utf-8 -*-
"""Generate a Windows version resource for PyInstaller ``EXE(version=...)``.

PyInstaller's ``EXE`` accepts either a ``VSVersionInfo`` object or the path
to a text file whose content is a Python expression evaluating to a
``VSVersionInfo`` (see ``PyInstaller.utils.win32.versioninfo``). This module
writes such a text file from the single source of truth
``pi_manager/extras.py`` -> ``APP_VERSION``.

Windows-only in practice; the module itself is importable on any platform.
"""
from __future__ import annotations

import re
from pathlib import Path

_APP_VERSION_RE = re.compile(r'APP_VERSION\s*=\s*"([^"]+)"')


def read_app_version(project_root: Path) -> str:
    """Extract APP_VERSION from pi_manager/extras.py (single source of truth)."""
    src = (project_root / "pi_manager" / "extras.py").read_text(encoding="utf-8")
    match = _APP_VERSION_RE.search(src)
    if not match:
        raise SystemExit("cannot extract APP_VERSION from pi_manager/extras.py")
    return match.group(1)


def _split_version(version: str) -> tuple[int, int, int, int]:
    parts = [int(p) if p.isdigit() else 0 for p in version.split(".")]
    parts = (parts + [0, 0, 0, 0])[:4]
    return (parts[0], parts[1], parts[2], parts[3])


def version_info_text(version: str) -> str:
    """VSVersionInfo(...) expression text understood by PyInstaller."""
    fv = _split_version(version)
    return f"""# UTF-8
#
# Auto-generated by scripts/pyi_version_info.py from pi_manager/extras.py
# (single source of truth: APP_VERSION). Do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={fv!r},
    prodvers={fv!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Pi Manager'),
        StringStruct('FileDescription', 'Pi Manager'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', 'PiManager'),
        StringStruct('OriginalFilename', 'PiManager.exe'),
        StringStruct('ProductName', 'Pi Manager'),
        StringStruct('ProductVersion', '{version}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def write_version_file(version: str, project_root: Path) -> str:
    """Write the version-info text file and return its absolute path."""
    out_dir = project_root / "build"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "version_info.txt"
    path.write_text(version_info_text(version), encoding="utf-8")
    return str(path)


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    print(write_version_file(read_app_version(root), root))
